lenguage: python
python:
    - "2.7"

install:
    "sudo pip install -r requerimientos.txt"

before_script:
    - autopep8 -ir *
    - flake8 --max-complexity=20 --exclude=*.txt,*.md *

script:
    - python CalculadoraTest.py
