---
before_script:
  - "autopep8 -ir *"
  - "flake8 --max-complexity=10 --exclude=*.txt,*.md,*.pyc,steps.py *"
install: "sudo pip install -r requerimientos.txt"
lenguage: python
python:
  - "2.7"
script:
  - "python CalculadoraTest.py"
  - "lettuce"
